stof_doctrine_extensions:
  default_locale: en_US
  orm:
    default:
      # tree: true
      sluggable: true
      softdeleteable: true
      timestampable: true # not needed: listeners are not enabled by default
